apiVersion: apps/v1
kind: Deployment
metadata:
  name: qod-db
  labels:
    app: qod-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qod-db
  template:
    metadata:
      labels:
        app: qod-db
    spec:
      containers:
        - name: qod-db
          image: saianilkumardeyyala/qod-db
          imagePullPolicy: Always
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          resources:
            limits:
              cpu: 10m
              memory: 28Mi
            requests:
              cpu: 10m
              memory: 28Mi
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
